require('module-alias/register');
global.compactLog=()=>{};
const db=require('@models');
let n=0,dbms=0,last='';
const orig=db.sequelize.query.bind(db.sequelize);
db.sequelize.query=async function(sql,opts){ n++; last=((typeof sql==='string'?sql:sql.query)||'').replace(/\s+/g,' ').slice(0,110); const t=Date.now(); try{return await orig(sql,opts);} finally{dbms+=Date.now()-t;} };
const ctrl=require('@controllers/superadmin/dashboard.controller');
const t0=Date.now();
const res={send:()=>{console.log(`DONE ${Date.now()-t0}ms | ${dbms}ms DB | ${n} queries`);process.exit(0);},status:()=>res};
const iv=setInterval(()=>console.log(`... ${Date.now()-t0}ms, ${n} queries, last: ${last}`),15000);
ctrl.summary({userId:Number(process.argv[2]),role:Number(process.argv[3]),query:{},params:{},body:{},headers:{}},res);
setTimeout(()=>{console.log('TIMEOUT after 150s,',n,'queries; last:',last);process.exit(1);},150000);
